// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package add_book

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"strings"
	"time"
	"xiazki/internal/model"
	"xiazki/web/template/components"
	"xiazki/web/template/layout"
)

type BookFormValues struct {
	Title        string `json:"title,omitempty" form:"title"`
	Authors      string `json:"authors,omitempty" form:"authors"`
	Tags         string `json:"tags,omitempty" form:"tags"`
	Translators  string `json:"translators,omitempty" form:"translators"`
	Narrators    string `json:"narrators,omitempty" form:"narrators"`
	Summary      string `json:"summary,omitempty" form:"summary"`
	ISBN10       string `json:"isbn10,omitempty" form:"isbn10"`
	ISBN13       string `json:"isbn13,omitempty" form:"isbn13"`
	Language     string `json:"language,omitempty" form:"language"`
	PublishDate  string `json:"publish_date,omitempty" form:"publish_date"`
	Publisher    string `json:"publisher,omitempty" form:"publisher"`
	PageCount    string `json:"page_count,omitempty" form:"page_count"`
	SeriesName   string `json:"series_name,omitempty" form:"series_name"`
	SeriesNumber string `json:"series_number,omitempty" form:"series_number"`
	CoverURL     string `json:"cover_url,omitempty" form:"cover_url"`
}

func (b BookFormValues) Validate() map[string]string {
	errors := make(map[string]string)
	if strings.TrimSpace(b.Title) == "" {
		errors["title"] = "Title is required"
	}
	if strings.TrimSpace(b.Authors) == "" {
		errors["authors"] = "At least one author is required"
	} else {
		authors := strings.Split(b.Authors, ",")
		validAuthors := 0
		for _, author := range authors {
			if strings.TrimSpace(author) != "" {
				validAuthors++
			}
		}
		if validAuthors == 0 {
			errors["authors"] = "At least one valid author is required"
		}
	}
	// TODO: validate ISBN10, ISBN13, PageCount, SeriesNumber, CoverURL
	return errors
}

func (b BookFormValues) ToBook() *model.Book {
	book := &model.Book{}

	// non-zero values only
	if b.Title != "" {
		book.Title = b.Title
	}
	if b.Authors != "" {
		authors := strings.Split(b.Authors, ",")
		for _, author := range authors {
			name := strings.TrimSpace(author)
			if name != "" {
				book.Authors = append(book.Authors, &model.Author{Name: name})
			}
		}
	}
	if b.Tags != "" {
		tags := strings.Split(b.Tags, ",")
		for _, tag := range tags {
			name := strings.TrimSpace(tag)
			if name != "" {
				book.Tags = append(book.Tags, &model.Tag{Name: name})
			}
		}
	}
	if b.Translators != "" {
		translators := strings.Split(b.Translators, ",")
		for _, translator := range translators {
			name := strings.TrimSpace(translator)
			if name != "" {
				book.Translators = append(book.Translators, &model.Translator{Name: name})
			}
		}
	}
	if b.Narrators != "" {
		narrators := strings.Split(b.Narrators, ",")
		for _, narrator := range narrators {
			name := strings.TrimSpace(narrator)
			if name != "" {
				book.Narrators = append(book.Narrators, &model.Narrator{Name: name})
			}
		}
	}
	book.Summary = b.Summary
	book.ISBN10 = b.ISBN10
	book.ISBN13 = b.ISBN13
	book.Language = b.Language
	if pd, err := time.Parse("2006-01-02", b.PublishDate); err == nil {
		book.PublishDate = pd
	}
	book.Publisher = b.Publisher
	if pc, err := strconv.ParseInt(b.PageCount, 10, 64); err == nil {
		book.PageCount = pc
	}
	book.SeriesName = b.SeriesName
	if sn, err := strconv.ParseInt(b.SeriesNumber, 10, 64); err == nil {
		book.SeriesNumber = sn
	}
	book.CoverURL = b.CoverURL

	return book
}

func BookToBookFormValues(book model.Book) BookFormValues {
	b := BookFormValues{}

	b.Title = book.Title
	if len(book.Authors) > 0 {
		list := make([]string, len(book.Authors))
		for i, author := range book.Authors {
			list[i] = author.Name
		}
		b.Authors = strings.Join(list, ", ")
	}
	if len(book.Tags) > 0 {
		list := make([]string, len(book.Tags))
		for i, tag := range book.Tags {
			list[i] = tag.Name
		}
		b.Tags = strings.Join(list, ", ")
	}
	if len(book.Translators) > 0 {
		list := make([]string, len(book.Translators))
		for i, translator := range book.Translators {
			list[i] = translator.Name
		}
		b.Translators = strings.Join(list, ", ")
	}
	if len(book.Narrators) > 0 {
		list := make([]string, len(book.Narrators))
		for i, narrator := range book.Narrators {
			list[i] = narrator.Name
		}
		b.Narrators = strings.Join(list, ", ")
	}
	if book.Summary != "" {
		b.Summary = book.Summary
	}
	if book.ISBN10 != "" {
		b.ISBN10 = book.ISBN10
	}
	if book.ISBN13 != "" {
		b.ISBN13 = book.ISBN13
	}
	if book.Language != "" {
		b.Language = book.Language
	}
	if !book.PublishDate.IsZero() {
		b.PublishDate = book.PublishDate.Format("2006-01-02")
	}
	if book.Publisher != "" {
		b.Publisher = book.Publisher
	}
	if book.PageCount != 0 {
		b.PageCount = strconv.FormatInt(int64(book.PageCount), 10)
	}
	if book.SeriesName != "" {
		b.SeriesName = book.SeriesName
	}
	if book.SeriesNumber != 0 {
		b.SeriesNumber = strconv.FormatInt(int64(book.SeriesNumber), 10)
	}
	if book.CoverURL != "" {
		b.CoverURL = book.CoverURL
	}

	return b
}

type Operation string

const (
	Add  = "add"
	Edit = "edit"
)

type Data struct {
	Op     Operation
	BookID int64
	Errors map[string]string
	Values BookFormValues
}

func Show(data Data) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		title := map[Operation]string{Add: "Add Book", Edit: "Edit Book"}
		h1 := map[Operation]string{Add: "Add New Book", Edit: "Edit Book"}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-background-soft mx-auto max-w-4xl rounded-lg p-6 shadow-sm\"><div class=\"mb-6 flex items-center justify-between\"><h1 class=\"text-foreground mb-6 text-2xl font-bold\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(h1[data.Op])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/template/add_book/show.templ`, Line: 202, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><button type=\"button\" class=\"bg-green hover:bg-green-light focus:ring-green-light text-background0 cursor-pointer rounded-md px-4 py-2 text-sm font-semibold transition-colors duration-200 focus:outline-none focus:ring-2\" hx-get=\"/add_book/autofill\" hx-target=\"#modal\" hx-swap=\"innerHTML\">Autofill</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Op == Add {
				templ_7745c5c3_Err = FormAdd(data).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if data.Op == Edit {
				templ_7745c5c3_Err = FormEdit(data).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(title[data.Op]).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FormAdd(data Data) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form class=\"max-w-2xl space-y-6\" hx-post=\"/add_book\" hx-target=\"this\" hx-swap=\"outerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = BookFormFields(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<button type=\"submit\" class=\"bg-blue hover:bg-blue-light focus:ring-blue-light text-background w-full rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-offset-2\">Add Book</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FormEdit(data Data) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<form class=\"max-w-2xl space-y-6\" hx-put=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue("/book/" + strconv.FormatInt(data.BookID, 10) + "/edit")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/template/add_book/show.templ`, Line: 242, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" hx-target=\"this\" hx-swap=\"outerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = BookFormFields(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"flex justify-end\"><button type=\"submit\" class=\"bg-blue hover:bg-blue-light focus:ring-blue-light text-background w-full rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-offset-2\">Edit Book</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func BookFormFields(data Data) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		Values := data.Values
		Errors := data.Errors
		templ_7745c5c3_Err = components.Input("title", "Title", "", "text", Errors, Values.Title).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("authors", "Authors (comma separated)", "", "text", Errors, Values.Authors).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("tags", "Tags (comma separated)", "", "text", Errors, Values.Tags).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("translators", "Translators (comma separated)", "", "text", Errors, Values.Translators).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("narrators", "Narrators (comma separated)", "", "text", Errors, Values.Narrators).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("summary", "Summary", "", "textarea", Errors, Values.Summary).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"grid grid-cols-1 gap-6 md:grid-cols-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("isbn10", "ISBN10", "", "text", Errors, Values.ISBN10).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("isbn13", "ISBN13", "", "text", Errors, Values.ISBN13).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("language", "Language", "ISO code", "text", Errors, Values.Language).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"grid grid-cols-1 gap-6 md:grid-cols-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("publisher", "Publisher", "", "text", Errors, Values.Publisher).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("publish_date", "Publish Date", "", "date", Errors, Values.PublishDate).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("page_count", "Page Count", "", "number", Errors, Values.PageCount).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><div class=\"grid grid-cols-1 gap-6 md:grid-cols-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("series_name", "Series Name", "", "text", Errors, Values.SeriesName).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("series_number", "Series Number", "", "number", Errors, Values.SeriesNumber).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("cover_url", "Cover URL", "", "url", Errors, Values.CoverURL).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
